checking polaris CLI installation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -22,55 +22,55 @@ env:
 before_install:
   # Boot the emulator by ID
   - |
-     ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
-     xcrun simctl boot $ios_uid
-  # List all emulator available
-  - xcrun simctl list
-  # Update the brew and build dependencies tools
-  # - brew outdated carthage || brew upgrade carthage
-  - brew update && brew upgrade carthage
-  - carthage version
-  - carthage update --platform ios --use-xcframeworks --no-use-binaries --cache-builds
-  - gem i slather
-  # Install build output formatting tool
-  - gem install xcpretty
-  # Force to update the Swiftlint to the last stable version
-  - brew outdated swiftlint || brew upgrade swiftlint
-  # Print the swiftlint version
-  - swiftlint version
-  # Installing Jazzy
-  - gem install jazzy
-  # Installing Sourcekitten
-  - brew install sourcekitten
-script: |
-  set -o pipefail
-  set -e
-  # Define the destination emulator
-  destination="platform=$platform,OS=$ios_version,name=$ios_device"
-  # Build and test Framework in Debug
-  xcodebuild -enableCodeCoverage "$code_coverage" clean build test -project "$PROJECT" \
-    -scheme "$scheme" \
-    -destination "$destination" \
-    -configuration "$configuration" ONLY_ACTIVE_ARCH="$only_active_arch" ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
-    | xcpretty --color
-  # Lint - Add `--strict` to fail for warning and violation
-  swiftlint lint --strict --reporter json
-after_success:
-- |
-  if [ "$code_coverage" == "YES" ]; then
-      slather;
-  fi
-  if [ "$publish_docs" == "YES" ]; then
-      if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
-          make docs;
-          sh ./Scripts/travisPublishDocs.sh;
-      fi
-  fi
-script: |
+#      ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
+#      xcrun simctl boot $ios_uid
+#   # List all emulator available
+#   - xcrun simctl list
+#   # Update the brew and build dependencies tools
+#   # - brew outdated carthage || brew upgrade carthage
+#   - brew update && brew upgrade carthage
+#   - carthage version
+#   - carthage update --platform ios --use-xcframeworks --no-use-binaries --cache-builds
+#   - gem i slather
+#   # Install build output formatting tool
+#   - gem install xcpretty
+#   # Force to update the Swiftlint to the last stable version
+#   - brew outdated swiftlint || brew upgrade swiftlint
+#   # Print the swiftlint version
+#   - swiftlint version
+#   # Installing Jazzy
+#   - gem install jazzy
+#   # Installing Sourcekitten
+#   - brew install sourcekitten
+# script: |
+#   set -o pipefail
+#   set -e
+#   # Define the destination emulator
+#   destination="platform=$platform,OS=$ios_version,name=$ios_device"
+#   # Build and test Framework in Debug
+#   xcodebuild -enableCodeCoverage "$code_coverage" clean build test -project "$PROJECT" \
+#     -scheme "$scheme" \
+#     -destination "$destination" \
+#     -configuration "$configuration" ONLY_ACTIVE_ARCH="$only_active_arch" ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
+#     | xcpretty --color
+#   # Lint - Add `--strict` to fail for warning and violation
+#   swiftlint lint --strict --reporter json
+# after_success:
+# - |
+#   if [ "$code_coverage" == "YES" ]; then
+#       slather;
+#   fi
+#   if [ "$publish_docs" == "YES" ]; then
+#       if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
+#           make docs;
+#           sh ./Scripts/travisPublishDocs.sh;
+#       fi
+#   fi
+# polaris:
   echo "Downloading Polaris Start"
   curl ifconfig.me 
-  curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
-  unzip -d /tmp -jo polaris_cli-linux64.zip
+  curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-macosx.zip
+  unzip -d /tmp -jo polaris_cli-macosx.zip
   echo "Downloading Polaris Complete"
 
   echo "Setup Polaris Start"
